[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
    "src/=src/",
    "@eigenlayer-middleware/=lib/eigenlayer-middleware/src/",
    "@openzeppelin-utils/=lib/openzeppelin-contracts/contracts/utils/",
    "@sp1-helios/=lib/sp1-helios/contracts/src/",
    "@sp1-contracts/=lib/sp1-helios/contracts/lib/sp1-contracts/contracts/src/",
    "@optimism/=lib/optimism/packages/contracts-bedrock/src/"
]

fs_permissions = [{ access = "read", path = "." }]

[rpc_endpoints]
holesky = "https://ethereum-holesky-rpc.publicnode.com"