[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
    "@eigenlayer-middleware/=lib/eigenlayer-middleware/src/",
    "@openzeppelin-utils/=lib/openzeppelin-contracts/contracts/utils/",
    "@sp1-helios/=lib/sp1-helios/contracts/src/",
    "@sp1-contracts/=lib/sp1-helios/contracts/lib/sp1-contracts/contracts/src/",
    "@optimism/=lib/optimism/packages/contracts-bedrock/src/"
]

# I can't tell why foundry wants the path to be exact but it does not work for me
fs_permissions = [
    { access = "read", path = "./" },
    { access = "write", path = "./" },
    { access = "read", path = "./artifacts/middlewareDataProof.json" },  # This is stupid
    { access = "read", path = "./.nodes/operator_keys/testacc1.private.bls.key.json" },
    { access = "read", path = "./.nodes/operator_keys/testacc1.bls.key.json" },
    { access = "read", path = "./.nodes/operator_keys/testacc1.ecdsa.key.json" },
    { access = "read", path = "./.nodes/operator_keys/testacc2.private.bls.key.json" },
    { access = "read", path = "./.nodes/operator_keys/testacc2.bls.key.json" },
    { access = "read", path = "./.nodes/operator_keys/testacc2.ecdsa.key.json" },
    { access = "read", path = "./.nodes/operator_keys/testacc3.private.bls.key.json" },
    { access = "read", path = "./.nodes/operator_keys/testacc3.bls.key.json" },
    { access = "read", path = "./.nodes/operator_keys/testacc3.ecdsa.key.json" }
]

[rpc_endpoints]
holesky = "https://1rpc.io/holesky"